version: "2"

run:
  modules-download-mode: vendor
  build-tags:
    - containers_image_openpgp
    - exclude_graphdriver_btrfs
    - exclude_graphdriver_devicemapper

linters:
  enable:
    - bodyclose
    - depguard
    - forbidigo
    - gocritic
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - "ifElseChain"
        - "assignOp"
        - "appendAssign"
        - "singleCaseSwitch"
    importas:
      alias:
        - pkg: "github.com/opencontainers/image-spec/specs-go/v1"
          alias: "ocispecs"
        - pkg: "github.com/opencontainers/go-digest"
          alias: "digest"
    govet:
      enable:
        - nilness
        - unusedwrite
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/containerd/containerd/platforms"
              desc: The containerd platforms package was migrated to a separate module. Use github.com/containerd/platforms instead.
            - pkg: "io/ioutil"
              desc: The io/ioutil package has been deprecated.
    forbidigo:
      forbid:
        - pattern: ^context\.WithCancel(# use context\.WithCancelCause instead)?$
        - pattern: ^context\.WithDeadline(# use context\.WithDeadline instead)?$
        - pattern: ^context\.WithTimeout(# use context\.WithTimeoutCause instead)?$
        - pattern: ^ctx\.Err(# use context\.Cause instead)?$
        - pattern: ^fmt\.Errorf(# use errors\.Errorf instead)?$
        - pattern: ^platforms\.DefaultString(# use platforms\.Format(platforms\.DefaultSpec()) instead\.)?$
    gosec:
      excludes:
        - G115
        - G204
        - G402
      config:
        G306: "0644"
    testifylint:
      disable:
        - "empty"
        - "bool-compare"
        - "len"
        - "negative-positive"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      -
        linters:
          - revive
        text: stutters
      -
        linters:
          - revive
        text: empty-block
      -
        linters:
          - revive
        text: superfluous-else
      -
        linters:
          - revive
        text: unused-parameter
      -
        linters:
          - revive
        text: redefines-builtin-id
      -
        linters:
          - revive
        text: if-return

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
